### ISSUE TITLE
Touch Pad Mouse Scrolling Issue

### ISSUE THREAD

**Issue by hggz** [TrueZhuangJia/moonlight-ios#10]
**Is your feature request related to a problem? Please describe.**

Hello! First off, thank you very much for this awesome fork. The added enhancements for mobile custom touch controls is fantastic!

However I am noticing when using the touchpad with custom controls, that the mouse scrolling is a lot more tougher to activate than in the regular native Moonlight. 

I tend to have to start swiping up and down from the center of the screen in order to have the mouse movement begin tracking. 

Is there an easy way to customize this or is this intended?

**Describe the solution you'd like**

I would like to be able to easily activate the mouse tracking while using custom controls on the touch pad. Especially for games that work with a controller and mouse.

**Describe alternatives you've considered**

I haven't considered many alternatives but an open to suggestions.

**Additional context**
Here's a photo of my current settings

![image](https://github.com/user-attachments/assets/71281e56-d6da-4946-9a3f-124ca19201ce)

**Comment by TrueZhuangJia** [comment]
If you're referring to the two-finger scrolling gesture on a touchpad, here's how it functions:

There is a 150ms delay before scrolling begins after two fingers touch down. This brief pause is reserved for recognizing right-click gestures. In my testing environment, this 150ms latency is barely noticeable and provides a smooth experience, resolving conflicts between right-clicks and scrolling actions.

I recommend placing two fingers on the touchpad and waiting momentarily before starting to scroll. 
150ms is a comfortable threshold for me, hope you'll get used to it~

**Comment by TrueZhuangJia** [comment]
@hggz 
But the delay is indeed not appropriate for gaming that requires mouse scrolling.  I never considered that...

**Comment by hggz** [comment]
I was actually referring to the single touch scrolling. As an example, I'll play a game like world of Warcraft or final fantasy online, using the controller.

Sometimes I want to use the mouse to select an element on screen. It used to feel smoother in the main moonlight client, but I notice a delay / delayed responsiveness with this one.

**Comment by hggz** [comment]
Upon further testing, it might be because the button regions like L1/R1 and the thumb sticks, might be swallowing up the mouse touches. 

If I move the buttons out of the way and give me a clear space in the center, the single mouse movement becomes easier to trigger.

I'll use that as a work around for now but bringing this to your attention.

Thanks a lot, the thumb sticks and customization here are 1000% better than the original implementation!

Edit:

I'll just reduce the area of the L1/R1 sticks and thumb sticks and it works better.

Also the 2 finger tap you mentioned above works fine, I haven't noticed it impact my experience.

Closing this for now, thank you 🙏

**Comment by TrueZhuangJia** [comment]
@hggz 
Upon further testing, it might be because the button regions like L1/R1 and the thumb sticks, might be swallowing up the mouse touches.

Yes you're right, there's a "dead zone"  surrounding each of the controller buttons to prevent accidental mouse movement, this is same with the original moonlight-iOS. However, it does not apply to the customized on-screen none-controller button 
(which is completely coded by me, supports keyboard & mouse buttons).  You may try this kind of buttons if you prefer "no-swallow-up" mouse touches.

The mouse touch event will be easily activated when you slide the screen from a position with enough distance to the controller buttons

The original PR of OSC layout customization developed by:
https://github.com/King0fSpace/moonlight-ios-CustomOSC
came with a major bug , causing the DZ expand to a very large area, and the mouse touch movement became unresponsive.
I refactored that by defining a DZ surrounding each controller buttons 

![image](https://github.com/user-attachments/assets/ce47025f-c2df-4a7a-a82d-1ab8427d8bc0)

![image](https://github.com/user-attachments/assets/59e08289-3434-4cbd-9129-fcd54ac0c1c5)

The DZ size is related with button size & and a fixed factor (currently 3.0 ) as you see the code.
I didn't make this factor available as an option in the setting because there're already too many stuff in the menu.

Your question is a good one, I'll reopen it for the reference of anyone who're interested.

**Comment by TrueZhuangJia** [comment]
> Upon further testing, it might be because the button regions like L1/R1 and the thumb sticks, might be swallowing up the mouse touches.
> 
> If I move the buttons out of the way and give me a clear space in the center, the single mouse movement becomes easier to trigger.
> 
> I'll use that as a work around for now but bringing this to your attention.
> 
> Thanks a lot, the thumb sticks and customization here are 1000% better than the original implementation!
> 
> Edit:
> 
> I'll just reduce the area of the L1/R1 sticks and thumb sticks and it works better.
> 
> Also the 2 finger tap you mentioned above works fine, I haven't noticed it impact my experience.
> 
> Closing this for now, thank you 🙏

"I just noticed that you're an iOS developer. If you're interested in improving this fork, feel free to fork it. Specifically, features like on-screen button vibration (I use an iPad only), gyro controls, and physical game controller compatibility are areas I'm not very familiar with."

This fork is already available on app store. Your contribution may have chance to help more people
https://apps.apple.com/us/app/moonlight-zwm/id6590630545

**Comment by TrueZhuangJia** [comment]
@hggz 
One last thing. Would you mind starring my repo?
Thanks.

**Comment by hggz** [comment]
Yes to both 😉
